### ISSUE TITLE
NGram index dropped & created on every startup - 7.0.0 - beta 4

### ISSUE THREAD

**Issue by arildboifot** [JasperFx/marten#2914]
A small repro using Marten 7.0.0 beta 4 

```
using Marten;
using Microsoft.Extensions.Hosting;

var host = Host.CreateDefaultBuilder()
   .ConfigureServices((ctx, services) =>
    {
        services.AddMarten(opts =>
        {
            opts.Connection("xxx");
            opts.Schema.For<NGramDoc>().NgramIndex(x => x.NGramString);
        })
       .ApplyAllDatabaseChangesOnStartup()
       .UseLightweightSessions();
    })
   .Build();

await host.StartAsync();

public class NGramDoc
{
    public Guid Id { get; set; }
    public string NGramString { get; set; } = "";
}
```

**Comment by jeremydmiller** [comment]
This might have been fixed by other changes, but "works on my box"

**Comment by arildboifot** [comment]
Using the same setup as earlier I still see this issue on beta 5.

```
      drop index if exists public.mt_doc_ngramdoc_idx_ngram_ngramstring;
      CREATE INDEX mt_doc_ngramdoc_idx_ngram_ngramstring ON public.mt_doc_ngramdoc USING gin (public.mt_grams_vector( data ->> 'NGramString'));
```

**Comment by mysticmind** [comment]
@arildboifot Thanks for reporting that the issue still persists. We will have a look at it.

@jeremydmiller I will have a look at this.

**Comment by jeremydmiller** [comment]
Trying it again this evening, and "it works on my box" again. I can't reproduce this *at all* with V7. There is some Weasel changes coming that were part of fixing #2983, maybe those changes will help whatever is happening here. What I am seeing in that other issue is that some other configuration of PostgreSQL makes yet more changes to the DDL that we weren't yet accounting for in our comparison.

But for right now, with no workable reproduction, this has to be closed because nothing is actionable.
