### ISSUE TITLE
Unable to Represent Hierarchies with Foreign Keys

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#628]
I seem to be unable to represent graphs with referential integrity.

Let's say I want to represent a hierarchy of `Category` objects, such that each one points to its parent:

```
public class Category
{
    public Guid Id { get; set; }
    public Guid? ParentId { get; set; }
    public string Name { get; set; }
    ...
}
```
And my `MartenRegistry` contains:

```
For<Category>()
    .ForeignKey<Category>(x => x.ParentId);
```

When I call `ApplyAllConfiguredChangesToDatabase()`, and exception is thrown with `Cyclic dependency found`.

The workaround is to change the `Category` so that the parent is represented as another `Category`, rather than as a `Guid`. But that stores the entire hierarchy in a single database row.

Maybe I'm still thinking too much in the relational world, but is this by design? Is it normal to store large graphs as JSON in a single database row?

**Comment by jeremydmiller** [comment]
@cocowalla Yeah, we never considered this case. I don't think it's going to be a big deal to make it be able to recognize the relationship to itself, but in your case, I might opt for a pure relational model for that hierarchy. 

Or you could add the constraint yourself with raw SQL instead of using Marten's FK.

**Comment by jeremydmiller** [comment]
The fix for this is gonna be in 1.2.4 on nuget shortly.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/commit/cf117af509ede6b524be8924f2daa3554b6d8169

**Comment by cocowalla** [comment]
This seems to fix the error that was occurring when building the schema, but I still get a "`Cyclic dependency found`" error when actually querying data. Stack trace:

```
   at Marten.Util.EnumerableExtensions.Visit[T](T item, ISet`1 visited, ICollection`1 sorted, Func`2 dependencies, Boolean throwOnCycle)
   at Marten.Util.EnumerableExtensions.Visit[T](T item, ISet`1 visited, ICollection`1 sorted, Func`2 dependencies, Boolean throwOnCycle)
   at Marten.Util.EnumerableExtensions.TopologicalSort[T](IEnumerable`1 source, Func`2 dependencies, Boolean throwOnCycle)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping)
   at Marten.Schema.DocumentSchema.EnsureStorageExists(Type documentType)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.SingleAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Marten.QueryableExtensions.SingleAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken token)
```
