### ISSUE TITLE
DROP INDEX CONCURRENTLY must be first action in transaction

### ISSUE THREAD

**Issue by NicoKno** [JasperFx/marten#960]
I get an exception with the following code and I can't find the actual problem.
The code is running against a docker postgres:latest container which should be a Postgres 10.2 DB.

``` csharp
public async Task<int> CountAsync(string userId, string modulePackageId, DateTime bookingDate, DateTime expiryDate)
{
            var result = await _session.Query<TransactionEvent>().Where(transaction => transaction.UserId.Equals(userId, StringComparison.Ordinal) &&
                                                                           transaction.PackageId.Equals(modulePackageId, StringComparison.Ordinal) &&
                                                                           transaction.Timestamp >= bookingDate &&
                                                                           transaction.Timestamp < expiryDate &&
                                                                           transaction.BillingExecuted).CountAsync();

            return result;
}
```

The exception that is thrown:
```
0A000: DROP INDEX CONCURRENTLY must be first action in transaction) ---> Marten.MartenCommandException: Marten Command Failure:
-- Marten.Storage.DocumentTable
drop index concurrently if exists public.mt_doc_transactionevent_idx_timestamp;


-- Marten.Storage.DocumentTable
drop index concurrently if exists public.mt_doc_transactionevent_idx_user_id;


-- Marten.Storage.DocumentTable
drop index concurrently if exists public.mt_doc_transactionevent_idx_package_id;


-- Marten.Storage.DocumentTable
drop index concurrently if exists public.mt_doc_transactionevent_idx_contingent_id;

0A000: DROP INDEX CONCURRENTLY must be first action in transaction ---> Npgsql.PostgresException: 0A000: DROP INDEX CONCURRENTLY must be first action in transaction
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   --- End of inner exception stack trace ---
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.CountAsync(CancellationToken token)
   at Marten.QueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken token)
```

**Comment by jeremydmiller** [comment]
@NicoKno I don't have enough information here to troubleshoot it, so I'm pulling this out of 2.6.0. I'd guess that Marten is detecting that there's either an index in the DB that no longer exists according to the configuration, or is trying to drop it and recreate it on startup. You might need to help Marten out by tearing down that index by hand first. You might start by having Marten generate the full patch of what it thinks is the difference between the database and what Marten things it should be. That should at least point at what indexes have changed or gone away.

**Comment by Miggleness** [comment]
Added test to reproduce issue.  It also uses auto-create 'CreateOrUpdate' behavior, which I understand shouldn't do any object drop on the schema.

**Comment by jeremydmiller** [comment]
Fixed with https://github.com/JasperFx/marten/pull/1006

**Comment by Fluwit** [comment]
This issue still exists in version 3.3.0 with Postgres and long, dynamically generated index names. 

When Marten generates an index name longer than the 63 characters permitted by Postgres, the TableDelta.compareIndices method always yields comparison conflicts. This happens because Postgres truncates the generated index name to 63 characters when the create index SQL statement is run. However, the compareIndices method's expected index name is not truncated.

I can look into fixing it, if you're good with that, @jeremydmiller?

**Comment by oskardudycz** [comment]
@KrisJJC PRs with fixes are always more than welcome!

**Comment by jeremydmiller** [comment]
The original issue **is** fixed. I'm opening a new issue for what @KrisJJC reported as it's a separate problem.
